I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 672, in script
    call screen dream(get_epilogue(), ['Continue'])
  File "renpy/common/000statements.rpy", line 662, in execute_call_screen
    args, kwargs = a.evaluate()
  File "game/script.rpy", line 672, in <module>
    call screen dream(get_epilogue(), ['Continue'])
  File "game/script.rpy", line 362, in get_epilogue
    output = event_flag['text']
UnboundLocalError: local variable 'event_flag' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 672, in script
    call screen dream(get_epilogue(), ['Continue'])
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 662, in execute_call_screen
    args, kwargs = a.evaluate()
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/ast.py", line 344, in evaluate
    value = renpy.python.py_eval(v, locals=scope)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/brent/dataville-renpy/renpy-8.1.3-sdk/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 672, in <module>
    call screen dream(get_epilogue(), ['Continue'])
  File "game/script.rpy", line 362, in get_epilogue
    output = event_flag['text']
UnboundLocalError: local variable 'event_flag' referenced before assignment

Linux-6.5.0-25-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.1.3.23091805
DataVille 1.0
Sun Mar 17 14:09:38 2024
